version: '3'

services:
  redisservice:
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  desafio-rate-limiter-app:
    container_name: desafio-rate-limiter-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redisservice:6379
    depends_on:
      redisservice:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - .:/app